In [1]:
import pandas as pd

In [5]:
s=pd.Series(["Hiba", "Balach", "Anas", "Sana", "Hadi","Bilal"] , index=["h", "b", "a", "s", "h", "b"])
s

h      Hiba
b    Balach
a      Anas
s      Sana
h      Hadi
b     Bilal
dtype: object

In [7]:

data={
"Name":["Hiba", "Balach", "Anas", "Sana", "Hadi","Bilal"], 
"Age":[25,30, 24, 22, 22, 17]
    
    
}

df=pd.DataFrame(data)
df

     Name  Age
0    Hiba   25
1  Balach   30
2    Anas   24
3    Sana   22
4    Hadi   22
5   Bilal   17

In [9]:
pd.read_csv("https://gist.githubusercontent.com/ryanorsinger/0c702f67dfe59346cd4677cd24f7aec7/raw/429f0d47856670e57b31d1f78a1abc54c889c7ca/tips.csv")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
df=pd.read_excel("quran.xlsx")
df.head(10)

,code,status,data.number,data.name,data.englishName,data.englishNameTranslation,data.numberOfAyahs,data.revelationType
0,200,OK,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
1,200,OK,6,سُورَةُ الأَنۡعَامِ,Al-An'aam,The Cattle,165,Meccan
2,200,OK,7,سُورَةُ الأَعۡرَافِ,Al-A'raaf,The Heights,206,Meccan
3,200,OK,10,سُورَةُ يُونُسَ,Yunus,Jonas,109,Meccan
4,200,OK,11,سُورَةُ هُودٍ,Hud,Hud,123,Meccan
5,200,OK,12,سُورَةُ يُوسُفَ,Yusuf,Joseph,111,Meccan
6,200,OK,14,سُورَةُ إِبۡرَاهِيمَ,Ibrahim,Abraham,52,Meccan
7,200,OK,15,سُورَةُ الحِجۡرِ,Al-Hijr,The Rock,99,Meccan
8,200,OK,16,سُورَةُ النَّحۡلِ,An-Nahl,The Bee,128,Meccan
9,200,OK,17,سُورَةُ الإِسۡرَاءِ,Al-Israa,The Night Journey,111,Meccan

In [13]:
pd.read_csv("quran.csv")

,code,status,data.number,data.name,data.englishName,data.englishNameTranslation,data.numberOfAyahs,data.revelationType
0,200,OK,1,??????? ????????????,Al-Faatiha,The Opening,7,Meccan
1,200,OK,6,??????? ???????????,Al-An'aam,The Cattle,165,Meccan
2,200,OK,7,??????? ???????????,Al-A'raaf,The Heights,206,Meccan
3,200,OK,10,??????? ???????,Yunus,Jonas,109,Meccan
4,200,OK,11,??????? ?????,Hud,Hud,123,Meccan
...,...,...,...,...,...,...,...,...
109,200,OK,66,??????? ????????????,At-Tahrim,The Prohibition,12,Medinan
110,200,OK,76,??????? ??????????,Al-Insaan,Man,31,Medinan
111,200,OK,98,??????? ???????????,Al-Bayyina,The Evidence,8,Medinan
112,200,OK,99,??????? ?????????????,Az-Zalzala,The Earthquake,8,Medinan
113,200,OK,110,??????? ?????????,An-Nasr,Divine Support,3,Medinan

In [21]:
raw=pd.read_json("http://api.alquran.cloud/v1/surah")

df=pd.json_normalize(raw["data"])

mys=df.head(15)
mys.to_csv("mysurahindexless.csv",index=False)